### ISSUE TITLE
Some issue

### ISSUE THREAD

**Issue by Johnnywick1** [astudentinearth/weather-app#1]
Hi,

Nice app, but there is some issue with time. In hourly weather app shows always my local time, not the time of the city i choose..

Regards

**Comment by astudentinearth** [comment]
Hi, this was one of the things I took into consideration but haven't implemented yet. I will likely add a switch for the timezone soon.

**Comment by astudentinearth** [comment]
Closing as this feature is now live. Feel free to reopen or create a new issue if problems arise❤️

**Comment by Johnnywick1** [comment]
Thank you

**Comment by Johnnywick1** [comment]
There is another issue: When i choose some location and there are 3 with the same name in the same country I dont know which location choose. There is no state or voivodeship for this location.

**Comment by Johnnywick1** [comment]
Another idea: is there a chance when I enter website the location will be search automatically by user IP?

**Comment by astudentinearth** [comment]
I think about reworking location search to include more details about administration and support other languages, as it only performs searches in English right now. It should remember recent searches as well.
Automatic location will be added soon as well

**Comment by astudentinearth** [comment]
These features are now live, it should ask for location permission when the page loads. Search is now improved to include the missing details too.
Keeping this issue open in case you have further suggestions :)
